name: Build Firmware
run-name: Build ESP32 Firmware images
env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  PACKAGE_NAME: esp32wol_builder
on: 
  push:
    paths-ignore:
      - 'builder/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Bundle python files
        run: |
          rm -R -f .dist
          mkdir -p .dist
          cp -R src/*.py .dist/
      - name: Prepare dist files
        run: python -c "import upload_mpy; upload_mpy.compile_and_minify(compile=False)"
      - name: Bundle static files
        run: python -m freezefs .dist/static .dist/frozen_static.py
      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build firmware
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.PACKAGE_NAME }}
          docker run --rm -v "$(pwd)/.dist":/mnt/source -v "$(pwd)/built":/mnt/built ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.PACKAGE_NAME }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware
          path: \
            ./built/*/micropython.bin
            ./built/*/bootloader/bootloader.bin
            ./built/*/partition_table/partition-table.bin
          if-no-files-found: error
          retention-days: 10
